### ISSUE TITLE
Undefined index: features

### ISSUE THREAD

**Issue by Muriano** [hackzilla-project/TicketBundleDemoApp#1]
When cloning and installing demo, an error is ocurred when executing post-install-cmd scripts, it says:

    [Symfony\Component\Debug\Exception\ContextErrorException]
    Notice: Undefined index: features

Script Sensio\Bundle\DistributionBundle\Composer\ScriptHandler::clearCache handling the post-install-cmd event terminated with an exception

    [RuntimeException]
    An error occurred when executing the ""cache:clear --no-warmup"" command:

    [Symfony\Component\Debug\Exception\ContextErrorException]
    Notice: Undefined index: features

**Comment by Muriano** [comment]
Sorry, I think i was uncomment them in config.yml, but i didn´t save.

**Comment by hackzilla** [comment]
Did you figure out that it was to do with this line in the config?

https://github.com/hackzilla/TicketBundleDemoApp/blob/master/app/config/config.yml#L83

**Comment by hackzilla** [comment]
Glad you found the solution 👍
